### ISSUE TITLE
Convert process doesn't work properly

### ISSUE THREAD

**Issue by SyntaxTalksToMe** [osadl/OSLOC2JSON#1]
Good day,

the converting process doesn't work properly. According to the description I create a txt File with the specific content. After that, I execute the python script with **python3 osloc2json.py FTL.txt**
But the process hangs and no json file is generated.

can anyone help?

Thanks in advance

**Comment by hex3262** [comment]
> According to the description I create a txt File with the specific content.

Why would you create a txt file? The goal of the osloc2json script is to convert an existing OSLOC checklist txt file.
Try:
```bash
wget https://www.osadl.org/fileadmin/checklists/unreflicenses/FTL.txt
./osloc2json.py FTL.txt
cat FTL.json
```
You will then see
```json
{
    "FTL": {
        "USE CASE": {
            "Binary delivery": {
                "YOU MUST": {
                    "Credit FreeType Team": {},
                    "Credit In Documentation FreeType Team": {}
                },
                "YOU MUST NOT": {
                    "Promote": {}
                }
            },
            "Source code delivery": {
                "IF": {
                    "Software modification": {
                        "YOU MUST": {
                            "Provide Modification report": {}
                        }
                    }
                },
                "YOU MUST": {
                    "Credit FreeType Team": {},
                    "Forward Copyright notices": {},
                    "Forward License text": {}
                },
                "YOU MUST NOT": {
                    "Modify License text": {},
                    "Promote": {}
                }
            }
        }
    }
}
```
However, you do not need to carry out the conversion yourself, as all OSLOC files are already available in JSON format. It is precisely for this that we have written the osloc2json script and run it on our server:
```bash
wget https://www.osadl.org/fileadmin/checklists/jsonlicenses/FTL.json
```
This is all explained [here](https://www.osadl.org/?id=3115).

By the way: I don't think you can use our checklist project professionally without having access to the project pages. For legal reasons, this access is only possible for registered users, but anyone can get such access. Just write to office@osadl.org.

**Comment by osadl** [comment]
Looks like the issue was resolved.
